package st61131.pru;

/*Generated by MPS */

import com.github.vlsi.pru.plc110.CodeEmitter;
import com.github.vlsi.pru.plc110.Format2Instruction;
import com.github.vlsi.pru.plc110.JumpInstruction;
import com.github.vlsi.pru.plc110.Label;
import com.github.vlsi.pru.plc110.LdiInstruction;
import com.github.vlsi.pru.plc110.MemoryTransferInstruction;
import com.github.vlsi.pru.plc110.Register;
import com.github.vlsi.pru.plc110.RegisterField;

import java.util.function.Consumer;

public class PRU_MM_CodeGenerator implements Consumer<CodeEmitter> {


  @Override
  public void accept(CodeEmitter ce) {
    Label startWhileBody0 = new Label("startWhileBody0");
    Label endWhile1 = new Label("endWhile1");
    ce.visitInstruction(
        new LdiInstruction(new Register(1, RegisterField.w0), (short) 65535).setComment("a => R1"));
    ce.visitInstruction(
        new LdiInstruction(new Register(1, RegisterField.w2), (short) 65535).setComment(""));
    ce.visitInstruction(
        new LdiInstruction(new Register(2, RegisterField.dw), (short) 0).setComment("b => R2"));
    ce.visitLabel(startWhileBody0);
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("a => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        4).encode().setComment("b => R2"));


    ce.visitInstruction(new JumpInstruction(Format2Instruction.Operation.JMP, startWhileBody0,
        new Register(1, RegisterField.dw)).setComment(""));
    ce.visitLabel(endWhile1);


  }
}
