package st61131.pru;

/*Generated by MPS */

import com.github.vlsi.pru.plc110.CodeEmitter;
import com.github.vlsi.pru.plc110.Label;
import com.github.vlsi.pru.plc110.LdiInstruction;
import com.github.vlsi.pru.plc110.MemoryTransferInstruction;
import com.github.vlsi.pru.plc110.QuickBranchInstruction;
import com.github.vlsi.pru.plc110.Register;
import com.github.vlsi.pru.plc110.RegisterField;

import java.util.function.Consumer;

public class PRU_TIMING_TEST_CodeGenerator implements Consumer<CodeEmitter> {
  @Override
  public void accept(CodeEmitter ce) {
    Label startWhileBody0 = new Label("startWhileBody0");
    Label endIf2 = new Label("endIf2");
    Label endWhile1 = new Label("endWhile1");
    ce.visitInstruction(
        new LdiInstruction(new Register(1, RegisterField.dw), (short) 28684).setComment(
            "controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(2, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        0).setLength(4).encode().setComment("v0 => R2, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(3, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        0).setLength(4).encode().setComment("v1 => R3, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(4, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        0).setLength(4).encode().setComment("v2 => R4, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(5, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        0).setLength(4).encode().setComment("v3 => R5, controlRegister => R1"));
    // v3=15

    ce.visitInstruction(
        new LdiInstruction(new Register(6, RegisterField.dw), (short) 0).setComment("zero => R6"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(4).setLength(
        4).encode().setComment("v0 => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(3, RegisterField.dw)).setAddress(3).setOffset(8).setLength(
        4).encode().setComment("v1 => R3"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(4, RegisterField.dw)).setAddress(3).setOffset(12).setLength(
        4).encode().setComment("v2 => R4"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(5, RegisterField.dw)).setAddress(3).setOffset(16).setLength(
        4).encode().setComment("v3 => R5"));

    ce.visitInstruction(
        new LdiInstruction(new Register(1, RegisterField.dw), (short) 28672).setComment(
            "controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(2, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v0 => R2, controlRegister => R1"));
    // v0=29 == 15 + 14
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(3, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v1 => R3, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(4, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v2 => R4, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(5, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v3 => R5, controlRegister => R1"));

    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(20).setLength(
        4).encode().setComment("v0 => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(3, RegisterField.dw)).setAddress(3).setOffset(24).setLength(
        4).encode().setComment("v1 => R3"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(4, RegisterField.dw)).setAddress(3).setOffset(28).setLength(
        4).encode().setComment("v2 => R4"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(5, RegisterField.dw)).setAddress(3).setOffset(32).setLength(
        4).encode().setComment("v3 => R5"));

    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(2, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v0 => R2, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(6, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("zero => R6, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(3, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v1 => R3, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(6, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("zero => R6, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(4, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v2 => R4, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(6, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("zero => R6, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(5, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(4).encode().setComment("v3 => R5, controlRegister => R1"));

    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(36).setLength(
        4).encode().setComment("v0 => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(3, RegisterField.dw)).setAddress(3).setOffset(40).setLength(
        4).encode().setComment("v1 => R3"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(4, RegisterField.dw)).setAddress(3).setOffset(44).setLength(
        4).encode().setComment("v2 => R4"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(5, RegisterField.dw)).setAddress(3).setOffset(48).setLength(
        4).encode().setComment("v3 => R5"));

    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(2, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(2).encode().setComment("v0 => R2, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(52).setLength(
        2).encode().setComment("v0 => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(3, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(2).encode().setComment("v1 => R3, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(3, RegisterField.dw)).setAddress(3).setOffset(56).setLength(
        2).encode().setComment("v1 => R3"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(4, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(2).encode().setComment("v2 => R4, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(4, RegisterField.dw)).setAddress(3).setOffset(60).setLength(
        2).encode().setComment("v2 => R4"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(5, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(2).encode().setComment("v3 => R5, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(5, RegisterField.dw)).setAddress(3).setOffset(64).setLength(
        2).encode().setComment("v3 => R5"));

    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(2, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(1).encode().setComment("v0 => R2, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(2, RegisterField.dw)).setAddress(3).setOffset(68).setLength(
        1).encode().setComment("v0 => R2"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(3, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(1).encode().setComment("v1 => R3, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(3, RegisterField.dw)).setAddress(3).setOffset(72).setLength(
        1).encode().setComment("v1 => R3"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(4, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(1).encode().setComment("v2 => R4, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(4, RegisterField.dw)).setAddress(3).setOffset(76).setLength(
        1).encode().setComment("v2 => R4"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(5, RegisterField.dw)).setAddress(new Register(1, RegisterField.dw)).setOffset(
        12).setLength(1).encode().setComment("v3 => R5, controlRegister => R1"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(5, RegisterField.dw)).setAddress(3).setOffset(80).setLength(
        1).encode().setComment("v3 => R5"));

    ce.visitLabel(startWhileBody0);
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.LOAD,
        new Register(1, RegisterField.b0)).setAddress(3).setOffset(0).setLength(
        1).encode().setComment("dataReady => R1.b0"));
    ce.visitInstruction(new QuickBranchInstruction(QuickBranchInstruction.Operation.EQ, endIf2,
        new Register(1, RegisterField.b0), 0).setComment("dataReady => R1.b0"));
    ce.visitInstruction(new LdiInstruction(new Register(1, RegisterField.b0), (short) 0).setComment(
        "dataReady => R1.b0"));
    ce.visitInstruction(new MemoryTransferInstruction(MemoryTransferInstruction.Operation.STORE,
        new Register(1, RegisterField.b0)).setAddress(3).setOffset(0).setLength(
        1).encode().setComment("dataReady => R1.b0"));

    ce.visitLabel(endIf2);


    ce.visitInstruction(new QuickBranchInstruction(startWhileBody0).setComment(""));
    ce.visitLabel(endWhile1);


  }
}
